# configures the tile used
tile_id: '13TDE'

# configures the satellite used
satellite: 'sentinel2' # 'sentinel2' or 'landsat8'

# if you wish to run the pipeline for hand selected dates
# you can specify them here (using yml array syntax)
dates: [ ]

inference:

  # if set to 0, the inference is skipped
  enable_inference: 1 # 0 or 1

  # model name, if left empty the default model will be used (unet.pth)
  model_file_name: 'unet_a82e3cd_ep30.pth' # 'unet_1c88144_e40.pth'

  # limits number of patches to be processed, if set to 0, all patches will be processed
  # this is helpful to debug the pipeline, for production this should be set to 0
  limit_patches: 0

  # use all rotations
  # if enabled, the model will be run on all rotations of the patches
  # and the results will be averaged, this improves the accuracy of the model
  # --> see final report
  use_all_rotations: 1

  save_raw_predictions: 0 # save raw predictions as float16 jp2 images
  save_raw_thresholded: 0 # save raw predictions as uint8 jp2 images

  # save TCI and FCI for processed s2 dates
  save_RGB_jp2_images: 1
  save_data_coverage: 1
  save_mask: 0