data_handling:

  # forces to download the raw data from the pf-server (1 or 0)
  # on Euler this must be set to 0
  force_rsync: 0

  # use single quotes for the dates and the array syntax
  s2_dates: ['20211008T101829', '20210710T101559', '20210106T102411', '20210406T102021']

annotation:

  # use the auto annotator to create the ground truth (1 or 0)
  auto_annotation: 1

dataset:

  recreate_dataset: 1