inference:

  enable_inference: 1

  # this date is used for inference in the new mode
  # if empty inference is run for all dates for the specified tile
  s2_dates: [ '20210126T102311' ]

  # model name, if left empty the default model will be used (unet.pth)
  model_file_name: 'unet_a82e3cd_ep30.pth' # 'unet_1c88144_e40.pth'

  # limits the patches, 0 stands for the whole tile
  # this option is only used in the new mode
  limit_patches: 0

  # use all rotations
  # if enabled, the model will be run on all rotations of the patches
  # and the results will be averaged, this improves the accuracy of the model
  use_all_rotations: 1

  save_raw_predictions: 1 # save raw predictions as float16 jp2 images
  save_raw_thresholded: 1 # save raw predictions as uint8 jp2 images

  # save TCI and FCI for processed s2 dates
  save_RGB_jp2_images: 1
  save_data_coverage: 1

# Enable testing if you wish to test the model's performance.
testing:

  enable_testing: 0
  use_cache: 0 # skips comparison and use cached results to recreate plots

  # those dates must be included in the s2_dates of the inference step, otherwise the testing will fail
  s2_dates: [ '20210126T102311' ]

# This is not yet implemented
ensemble:

  # ensembles the predictions of different models
  # if enabled, all previous steps will be ignored
  enable: 0

  # the names of the masks to be used for the ensemble
  mask_names: [ '20211217T102329_mask_prediction_2d0d993_e36' ]
