data_handling:

  # forces to download the raw data from the pf-server (1 or 0)
  force_rsync: 0

  # use single quotes for the dates and the array syntax
  s2_dates: ['20210106T102411', '20210406T102021']