# [ignored on euler] deletes the results folder before starting the pipeline (1 or 0)
clear_results: 0

# this section describes the data handling, i.g. the preparation of the data:
# download and extraction, most of those settings will be ignored on euler
data_handling:

  # [ignored on euler] forces to download the raw data from the pf-server (1 or 0)
  # this will delete all old data and freshly download the s2_dates listed below
  # currently all data is manually downloaded to the pf-pc20
  # this was done using "cp -r /home/pf/pfstud/nimbus/download_data/* /scratch2/pucyril/bachelor-thesis/data/raw"
  force_rsync: 0

  # [ignored on euler] use single quotes for the dates and the array syntax
  # only those dates will be downloaded, does not influence the extraction
  s2_dates: [ '20211008T101829', '20210710T101559', '20210106T102411', '20210406T102021' ]

  # [ignored on euler] here the data handling is done separately (1 or 0)
  # extracts all data from the raw data folder to the tmp folder
  # currently all data has been extracted
  force_extraction: 0

# this section describes the preprocessing of the data
# e.g. if the masks should be created automatically or if
# some manual annotations should be used
annotation:

  # use the auto annotator to create the ground truth (1 or 0)
  # currently this computes the s2cloudless predictions which is very slow
  # then combines them with the ExoLab predictions
  auto_annotation: 0

  # masks will be only created for the following dates
  # if you wish to create masks for all dates, just leave the array empty
  s2_dates: [ ]

# This section describes the training and validation dataset creation/loading
dataset:

  # forces a recreation of the dataset (1 or 0)
  # this deletes the dataset folder and recreates it using the current raw data
  # will be ignored if create_on_the_fly is enabled
  recreate_dataset: 1

  # limits the number of dates to be used for the dataset
  # if you wish to use all dates, just set this to 0
  limit_dates: 0

  # this option will be used to select the dates
  # if you wish to create masks for all dates, just leave the array empty
  # if limit_dates is set to a value > 0, this option will be ignored
  s2_dates: [ '20210116T102351', '20210121T102239', '20210126T102311', '20210131T102149', '20210215T102121', '20210220T101939', '20210225T102021', '20210302T101839', '20210307T102021', '20210322T101649', '20210401T101559', '20210406T102021', '20210416T102021' ]

  # loads the data directly without creating the dataset (1 or 0)
  # if this option is enabled the recreate_dataset option will be ignored
  # in this mode, the dataloader will dynamically load the data from the raw folder
  # instead of creating and saving the images as patches, on Euler this is faster
  create_on_the_fly: 0