# [ignored on euler] deletes the results folder before starting the pipeline (1 or 0)
clear_results: 0

# this section describes the data handling, i.g. the preparation of the data:
# download and extraction, most of those settings will be ignored on euler
data_handling:

  # [ignored on euler] forces to download the raw data from the pf-server (1 or 0)
  # this will delete all old data and freshly download the s2_dates listed below
  # currently all data is manually downloaded to the pf-pc20
  # this was done using "cp -r /home/pf/pfstud/nimbus/download_data/* /scratch2/pucyril/bachelor-thesis/data/raw"
  force_rsync: 0

  # [ignored on euler] use single quotes for the dates and the array syntax
  # only those dates will be downloaded, does not influence the extraction
  s2_dates: [ '20211008T101829', '20210710T101559', '20210106T102411', '20210406T102021' ]

  # [ignored on euler] here the data handling is done separately (1 or 0)
  # extracts all data from the raw data folder to the tmp folder
  # currently all data has been extracted
  force_extraction: 0

annotation:

  # use the auto annotator to create the ground truth (1 or 0)
  # currently this computes the s2cloudless predictions which is very slow
  # then combines them with the ExoLab predictions
  auto_annotation: 1

  # masks will be only created for the following dates
  # if you wish to create masks for all dates, just leave the array empty
  s2_dates: [ ]


dataset:

  recreate_dataset: 0
