# configures the tile used
tile_id: '32TNS'

# configures the satellite used
satellite: 'sentinel2' # 'sentinel2' or 'landsat8'

# if you wish to run the pipeline for hand selected dates
# you can specify them here (using yml array syntax)
dates: [ ]

testing:

  # enables the testing (1 or 0)
  enable: 1
  model_name: 'unet_a82e3cd_ep30'
  use_cache: 0

