# configures the tile used
tile_id: '32VMP'

# configures the satellite used
satellite: 'sentinel2' # 'sentinel2' or 'landsat8'

# limit to landcover type
limit_to_landcover: 0
#  0: {name: ‘water’, color: ‘#419BDF’},
#  1: {name: ‘trees’, color: ‘#397D49’},
#  2: {name: ‘grass’, color: ‘#88B053’},
#  3: {name: ‘flooded_vegetation’, color: ‘#7A87C6’},
#  4: {name: ‘crops’, color: ‘#E49635’},
#  5: {name: ‘shrub_and_scrub’, color: ‘#DFC35A’},
#  6: {name: ‘built’, color: ‘#C4281B’},
#  7: {name: ‘bare’, color: ‘#A59B8F’},
#  8: {name: ‘snow_and_ice’, color: ‘#B39FE1’},
landcover_classes: [ 1 ] # we only include those
landcover_file: '32TNS_10m_landcover_DW_y-2021-2022_m-06-10.tif'

# if you wish to run the pipeline for hand selected dates
# you can specify them here (using yml array syntax)
dates: [ ]

testing:

  # enables the testing (1 or 0)
  enable: 1
  model_name: 'unet_a82e3cd_ep30.pth'
  use_cache: 0

  # compare to predictions
  compare_to_prediction: 0 # default is a comparison to the ExoLabs prediction
  prediction_name: 'mask_prediction'
  prediction_name_other: 'mask_prediction_60'

  difference_map_postfix: 'exolabs'
